IMFTypes.o: config.h Astro.h CELib.h IMFTypes.h Integral.h \
 LifeTime.h RunParameters.h Utilities.h
Info.o: config.h Astro.h CELib.h IMFTypes.h Integral.h LifeTime.h \
 RunParameters.h Utilities.h SNIaYields.h \
 ../data/Iwamoto+1999/Iwamoto+1999_Struct.h \
 ../data/Maeda+2010/Maeda+2010_Struct.h \
 ../data/Seitenzahl+2013/Seitenzahl+2013_Struct.h \
 ../data/Travaglio+2004/Travaglio+2004_Struct.h
WriteIMF.o: config.h Astro.h CELib.h IMFTypes.h Integral.h \
 LifeTime.h RunParameters.h Utilities.h IMFFunctions.h
Init.o: config.h Astro.h CELib.h IMFTypes.h Integral.h LifeTime.h \
 RunParameters.h Utilities.h CheckRunParameters.h IMFFunctions.h \
 SNIIYields.h SNIIRate.h SNIaYields.h SNIaRate.h NSMYields.h NSMRate.h \
 InitialMetallicity.h AGBMassLoss.h
YieldsInfo.o: config.h Astro.h CELib.h IMFTypes.h Integral.h \
 LifeTime.h RunParameters.h Utilities.h IMFFunctions.h SNIIYields.h \
 SNIaYields.h
LifeTime.o: config.h Astro.h CELib.h IMFTypes.h Integral.h \
 LifeTime.h RunParameters.h Utilities.h LifeTimeTable.h
IMFFunctions.o: config.h Astro.h CELib.h IMFTypes.h \
 Integral.h LifeTime.h RunParameters.h Utilities.h IMFFunctions.h
Integral.o: config.h Astro.h CELib.h IMFTypes.h Integral.h \
 LifeTime.h RunParameters.h Utilities.h
SNIIYields.o: config.h Astro.h CELib.h IMFTypes.h Integral.h \
 LifeTime.h RunParameters.h Utilities.h SNIIYields.h \
 ../data/Portinari+1998/Portinari+1998_Struct.h \
 ../data/Nomoto+2013/Nomoto+2013_Struct.h \
 ../data/Nomoto+2013/Nomoto+2013HN_Struct.h
SNIaYields.o: config.h Astro.h CELib.h IMFTypes.h Integral.h \
 LifeTime.h RunParameters.h Utilities.h SNIaYields.h \
 ../data/Iwamoto+1999/Iwamoto+1999_Struct.h \
 ../data/Maeda+2010/Maeda+2010_Struct.h \
 ../data/Seitenzahl+2013/Seitenzahl+2013_Struct.h \
 ../data/Travaglio+2004/Travaglio+2004_Struct.h
SNIIRate.o: config.h Astro.h CELib.h IMFTypes.h Integral.h \
 LifeTime.h RunParameters.h Utilities.h SNIIYields.h SNIIRate.h
SNIaRate.o: config.h Astro.h CELib.h IMFTypes.h Integral.h \
 LifeTime.h RunParameters.h Utilities.h SNIaYields.h SNIaRate.h
NSMYields.o: config.h Astro.h CELib.h IMFTypes.h Integral.h \
 LifeTime.h RunParameters.h Utilities.h NSMYields.h
NSMRate.o: config.h Astro.h CELib.h IMFTypes.h Integral.h \
 LifeTime.h RunParameters.h Utilities.h NSMYields.h NSMRate.h
InitialMetallicity.o: config.h Astro.h CELib.h \
 IMFTypes.h Integral.h LifeTime.h RunParameters.h Utilities.h \
 SNIIYields.h
AGBMassLoss.o: config.h Astro.h CELib.h IMFTypes.h \
 Integral.h LifeTime.h RunParameters.h Utilities.h AGBMassLoss.h \
 ../data/Karakas2010/Karakas2010_Struct.h \
 ../data/Doherty+2014/Doherty+2014_Struct.h \
 ../data/CampbellLattanzio2008/CampbellLattanzio2008_Struct.h \
 ../data/Gil-Pons+2013/Gil-Pons+2013_Struct.h \
 ../data/vandenHoekGroenewegen1997/vandenHoekGroenewegen1997_Struct.h
UnifiedAPIs.o: config.h Astro.h CELib.h IMFTypes.h \
 Integral.h LifeTime.h RunParameters.h Utilities.h
RunParameters.o: config.h Astro.h CELib.h IMFTypes.h \
 Integral.h LifeTime.h RunParameters.h Utilities.h Init.h IMFFunctions.h \
 SNIIYields.h SNIaYields.h
CheckRunParameters.o: config.h Astro.h CELib.h \
 IMFTypes.h Integral.h LifeTime.h RunParameters.h Utilities.h \
 SNIaYields.h ../data/Iwamoto+1999/Iwamoto+1999_Struct.h \
 ../data/Maeda+2010/Maeda+2010_Struct.h \
 ../data/Seitenzahl+2013/Seitenzahl+2013_Struct.h \
 ../data/Travaglio+2004/Travaglio+2004_Struct.h
Utilities.o: config.h Astro.h CELib.h IMFTypes.h Integral.h \
 LifeTime.h RunParameters.h Utilities.h
